/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const NotebookJsonObjectRemoteCodec$schema = z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))])).readonly()
const NotebookJsonObjectRemoteCodec$schema2 = z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))])).readonly()
const NotebookJsonObjectRemoteCodec$schema3 = z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))])).readonly()
const NotebookJsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))])
const NotebookJsonValueRemoteCodec$schema2 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))])
const NotebookJsonValueRemoteCodec$schema3 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))])
const _deepseek_ai_dsh_notebook_remote_notebooks_attachEnvironment_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'notebookId': z.string().readonly(),
  'environmentId': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_attachEnvironment_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.string().readonly(),
  'path': z.string().readonly(),
  'kernel': z.union([z.undefined(), z.object({
  'environmentId': z.string().readonly(),
  'backend': z.string().readonly(),
  'kernelName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generation': z.number().readonly(),
})]).readonly().optional(),
  'fileVersion': z.string().readonly(),
  'nbformatMinor': z.number().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))])).readonly().readonly(),
  'cells': z.array(z.object({
  'id': z.string().readonly(),
  'cellType': z.union([z.literal("code"), z.literal("markdown"), z.literal("raw")]).readonly(),
  'source': z.string().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))])).readonly().readonly(),
  'attachments': z.record(z.string(), z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly()).readonly().readonly(),
  'outputs': z.array(z.union([z.object({
  'type': z.literal("stream").readonly(),
  'name': z.union([z.literal("stdout"), z.literal("stderr")]).readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("display").readonly(),
  'data': z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))])).readonly().readonly(),
  'displayId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'type': z.literal("execute-result").readonly(),
  'data': z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema3), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema3))])).readonly().readonly(),
  'executionCount': z.union([z.literal(null), z.number()]).readonly(),
  'displayId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'type': z.literal("error").readonly(),
  'name': z.string().readonly(),
  'value': z.string().readonly(),
  'traceback': z.array(z.string()).readonly(),
})])).readonly(),
  'executionCount': z.union([z.undefined(), z.number()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("cancelled"), z.literal("error"), z.literal("running"), z.literal("ok")]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_create_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_create_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.string().readonly(),
  'path': z.string().readonly(),
  'kernel': z.union([z.undefined(), z.object({
  'environmentId': z.string().readonly(),
  'backend': z.string().readonly(),
  'kernelName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generation': z.number().readonly(),
})]).readonly().optional(),
  'fileVersion': z.string().readonly(),
  'nbformatMinor': z.number().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))])).readonly().readonly(),
  'cells': z.array(z.object({
  'id': z.string().readonly(),
  'cellType': z.union([z.literal("code"), z.literal("markdown"), z.literal("raw")]).readonly(),
  'source': z.string().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))])).readonly().readonly(),
  'attachments': z.record(z.string(), z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly()).readonly().readonly(),
  'outputs': z.array(z.union([z.object({
  'type': z.literal("stream").readonly(),
  'name': z.union([z.literal("stdout"), z.literal("stderr")]).readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("display").readonly(),
  'data': z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))])).readonly().readonly(),
  'displayId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'type': z.literal("execute-result").readonly(),
  'data': z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema2), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema2))])).readonly().readonly(),
  'executionCount': z.union([z.literal(null), z.number()]).readonly(),
  'displayId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'type': z.literal("error").readonly(),
  'name': z.string().readonly(),
  'value': z.string().readonly(),
  'traceback': z.array(z.string()).readonly(),
})])).readonly(),
  'executionCount': z.union([z.undefined(), z.number()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("cancelled"), z.literal("error"), z.literal("running"), z.literal("ok")]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_createEnvironment_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'environmentId': z.string().readonly(),
  'allowExisting': z.boolean().readonly(),
  'rebuild': z.boolean().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_createEnvironment_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'manager': z.object({
  'status': z.union([z.literal("ready"), z.literal("missing"), z.literal("broken"), z.literal("unsupported")]).readonly(),
  'version': z.union([z.undefined(), z.string()]).readonly().optional(),
  'canInstall': z.boolean().readonly(),
}).readonly(),
  'pythons': z.array(z.object({
  'id': z.string().readonly(),
  'version': z.string().readonly(),
  'source': z.union([z.literal("configured"), z.literal("path"), z.literal("managed")]).readonly(),
})).readonly(),
  'environments': z.array(z.object({
  'id': z.string().readonly(),
  'displayName': z.string().readonly(),
  'status': z.union([z.literal("ready"), z.literal("broken"), z.literal("setup-required"), z.literal("provisioning")]).readonly(),
  'pythonVersion': z.union([z.undefined(), z.string()]).readonly().optional(),
  'managed': z.boolean().readonly(),
})).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_discover_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'after': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_discover_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'items': z.array(z.object({
  'path': z.string().readonly(),
  'size': z.union([z.undefined(), z.number()]).readonly().optional(),
})).readonly(),
  'nextAfter': z.union([z.undefined(), z.string()]).readonly().optional(),
  'partial': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_editCell_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'notebookId': z.string().readonly(),
  'cellId': z.string().readonly(),
  'source': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_editCell_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'ok': z.literal(true).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_environmentCatalog_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_environmentCatalog_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'manager': z.object({
  'status': z.union([z.literal("ready"), z.literal("missing"), z.literal("broken"), z.literal("unsupported")]).readonly(),
  'version': z.union([z.undefined(), z.string()]).readonly().optional(),
  'canInstall': z.boolean().readonly(),
}).readonly(),
  'pythons': z.array(z.object({
  'id': z.string().readonly(),
  'version': z.string().readonly(),
  'source': z.union([z.literal("configured"), z.literal("path"), z.literal("managed")]).readonly(),
})).readonly(),
  'environments': z.array(z.object({
  'id': z.string().readonly(),
  'displayName': z.string().readonly(),
  'status': z.union([z.literal("ready"), z.literal("broken"), z.literal("setup-required"), z.literal("provisioning")]).readonly(),
  'pythonVersion': z.union([z.undefined(), z.string()]).readonly().optional(),
  'managed': z.boolean().readonly(),
})).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_insertCell_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'notebookId': z.string().readonly(),
  'cellType': z.union([z.literal("code"), z.literal("markdown"), z.literal("raw")]).readonly(),
  'afterCellId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'source': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_insertCell_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'cellId': z.string().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_installPython_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'version': z.literal("3.12").readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_installPython_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'manager': z.object({
  'status': z.union([z.literal("ready"), z.literal("missing"), z.literal("broken"), z.literal("unsupported")]).readonly(),
  'version': z.union([z.undefined(), z.string()]).readonly().optional(),
  'canInstall': z.boolean().readonly(),
}).readonly(),
  'pythons': z.array(z.object({
  'id': z.string().readonly(),
  'version': z.string().readonly(),
  'source': z.union([z.literal("configured"), z.literal("path"), z.literal("managed")]).readonly(),
})).readonly(),
  'environments': z.array(z.object({
  'id': z.string().readonly(),
  'displayName': z.string().readonly(),
  'status': z.union([z.literal("ready"), z.literal("broken"), z.literal("setup-required"), z.literal("provisioning")]).readonly(),
  'pythonVersion': z.union([z.undefined(), z.string()]).readonly().optional(),
  'managed': z.boolean().readonly(),
})).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_installUv_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_installUv_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'manager': z.object({
  'status': z.union([z.literal("ready"), z.literal("missing"), z.literal("broken"), z.literal("unsupported")]).readonly(),
  'version': z.union([z.undefined(), z.string()]).readonly().optional(),
  'canInstall': z.boolean().readonly(),
}).readonly(),
  'pythons': z.array(z.object({
  'id': z.string().readonly(),
  'version': z.string().readonly(),
  'source': z.union([z.literal("configured"), z.literal("path"), z.literal("managed")]).readonly(),
})).readonly(),
  'environments': z.array(z.object({
  'id': z.string().readonly(),
  'displayName': z.string().readonly(),
  'status': z.union([z.literal("ready"), z.literal("broken"), z.literal("setup-required"), z.literal("provisioning")]).readonly(),
  'pythonVersion': z.union([z.undefined(), z.string()]).readonly().optional(),
  'managed': z.boolean().readonly(),
})).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_interrupt_parameter_0$schema = z.object({
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sessionId': z.string().readonly(),
  'notebookId': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_interrupt_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'interrupted': z.boolean().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_open_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_open_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.string().readonly(),
  'path': z.string().readonly(),
  'kernel': z.union([z.undefined(), z.object({
  'environmentId': z.string().readonly(),
  'backend': z.string().readonly(),
  'kernelName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generation': z.number().readonly(),
})]).readonly().optional(),
  'fileVersion': z.string().readonly(),
  'nbformatMinor': z.number().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))])).readonly().readonly(),
  'cells': z.array(z.object({
  'id': z.string().readonly(),
  'cellType': z.union([z.literal("code"), z.literal("markdown"), z.literal("raw")]).readonly(),
  'source': z.string().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))])).readonly().readonly(),
  'attachments': z.record(z.string(), z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly()).readonly().readonly(),
  'outputs': z.array(z.union([z.object({
  'type': z.literal("stream").readonly(),
  'name': z.union([z.literal("stdout"), z.literal("stderr")]).readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("display").readonly(),
  'data': z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))])).readonly().readonly(),
  'displayId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'type': z.literal("execute-result").readonly(),
  'data': z.record(z.string(), z.union([z.object({
  'type': z.literal("text").readonly(),
  'text': z.string().readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))]).readonly(),
}), z.object({
  'type': z.literal("image").readonly(),
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'type': z.literal("base64").readonly(),
  'data': z.string().readonly(),
})])).readonly().readonly(),
  'metadata': z.record(z.string(), z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.lazy(() => NotebookJsonObjectRemoteCodec$schema), z.array(z.lazy(() => NotebookJsonValueRemoteCodec$schema))])).readonly().readonly(),
  'executionCount': z.union([z.literal(null), z.number()]).readonly(),
  'displayId': z.union([z.undefined(), z.string()]).readonly().optional(),
}), z.object({
  'type': z.literal("error").readonly(),
  'name': z.string().readonly(),
  'value': z.string().readonly(),
  'traceback': z.array(z.string()).readonly(),
})])).readonly(),
  'executionCount': z.union([z.undefined(), z.number()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("cancelled"), z.literal("error"), z.literal("running"), z.literal("ok")]).readonly().optional(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_readAttachment_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'attachmentId': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_readAttachment_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'attachment': z.object({
  'attachmentId': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'bytes': z.number().readonly(),
  'width': z.number().readonly(),
  'height': z.number().readonly(),
  'name': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'data': z.string().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_reload_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'notebookId': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_reload_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'fileVersion': z.string().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_restart_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'notebookId': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_restart_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'notebookId': z.string().readonly(),
  'environmentId': z.string().readonly(),
  'backend': z.string().readonly(),
  'kernelName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generation': z.number().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_runCell_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'notebookId': z.string().readonly(),
  'cellId': z.string().readonly(),
  'source': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_runCell_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'executionId': z.string().readonly(),
  'status': z.union([z.literal("cancelled"), z.literal("error"), z.literal("ok")]).readonly(),
  'executionCount': z.union([z.literal(null), z.number()]).readonly(),
  'error': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
})])
const _deepseek_ai_dsh_notebook_remote_notebooks_runtimeStatus_parameter_0$schema = z.object({
  'sessionId': z.string().readonly(),
  'notebookId': z.string().readonly(),
})
const _deepseek_ai_dsh_notebook_remote_notebooks_runtimeStatus_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'source': z.union([z.literal("session"), z.literal("core"), z.literal("persistence"), z.literal("environment"), z.literal("attachment"), z.literal("configuration"), z.literal("cancelled")]).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
  'category': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryable': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.object({
  'status': z.literal("detached").readonly(),
}), z.object({
  'status': z.union([z.literal("running"), z.literal("ready"), z.literal("starting"), z.literal("stopped")]).readonly(),
  'environmentId': z.string().readonly(),
}), z.object({
  'status': z.literal("failed").readonly(),
  'environmentId': z.string().readonly(),
  'message': z.string().readonly(),
})]).readonly(),
})])

export const TYPERT = {
  package: '@younthing/dsh-notebook-remote',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@younthing/dsh-notebook-remote#notebooks/attachEnvironment',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'attachEnvironment',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookAttachEnvironmentRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_attachEnvironment_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_attachEnvironment_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":434,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/create',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookCreateRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_create_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":355,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/createEnvironment',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'createEnvironment',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookCreateEnvironmentRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_createEnvironment_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_createEnvironment_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":410,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/discover',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'discover',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookDiscoverRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_discover_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_discover_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":324,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/editCell',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'editCell',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookEditCellRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_editCell_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_editCell_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":515,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/environmentCatalog',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'environmentCatalog',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookEnvironmentCatalogRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_environmentCatalog_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_environmentCatalog_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":366,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/insertCell',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'insertCell',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookInsertCellRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_insertCell_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_insertCell_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":535,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/installPython',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'installPython',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookInstallPythonRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_installPython_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_installPython_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":394,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/installUv',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'installUv',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookSessionRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_installUv_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_installUv_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":381,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/interrupt',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'interrupt',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookInterruptRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_interrupt_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_interrupt_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":635,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/open',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'open',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookOpenRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_open_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_open_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":344,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/readAttachment',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'readAttachment',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookReadAttachmentRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_readAttachment_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_readAttachment_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":477,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/reload',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'reload',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookIdentityRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_reload_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_reload_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":617,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/restart',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'restart',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookIdentityRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_restart_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_restart_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":591,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/runCell',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'runCell',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRunCellRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_runCell_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_runCell_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":563,"column":9},
    },
    {
      id: '@younthing/dsh-notebook-remote#notebooks/runtimeStatus',
      service: 'notebookRemote',
      namespace: 'notebooks',
      method: 'runtimeStatus',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRuntimeStatusRequest',
            schema: _deepseek_ai_dsh_notebook_remote_notebooks_runtimeStatus_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@younthing/dsh-notebook-remote/types#NotebookRemoteResult',
        schema: _deepseek_ai_dsh_notebook_remote_notebooks_runtimeStatus_result$schema,
      },
      sourceLocation: {"file":"packages/notebook-remote/src/index.ts","line":461,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Remote-only Notebook service under `ctx.remote.notebooks`.",
        "summary": "Remote-only Notebook service under `ctx.remote.notebooks`.",
        "tags": [],
        "jsDoc": "/** Remote-only Notebook service under `ctx.remote.notebooks`. */",
        "key": "notebookRemote",
        "exportName": "NotebookRemoteService",
        "members": [
          {
            "kind": "method",
            "name": "discover",
            "signature": "@Remote async discover(request: NotebookDiscoverRequest, signal: AbortSignal): Promise<NotebookRemoteResult<NotebookDiscoveryPage>>",
            "summary": "Discover workspace notebooks without activating a cold session.",
            "jsDoc": "/** Discover workspace notebooks without activating a cold session. */"
          },
          {
            "kind": "method",
            "name": "open",
            "signature": "@Remote async open(request: NotebookOpenRequest, signal: AbortSignal): Promise<NotebookRemoteResult<NotebookDocument>>",
            "summary": "Open an existing notebook in one exact session.",
            "jsDoc": "/** Open an existing notebook in one exact session. */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote async create(request: NotebookCreateRequest, signal: AbortSignal): Promise<NotebookRemoteResult<NotebookDocument>>",
            "summary": "Create an absent notebook in one exact session.",
            "jsDoc": "/** Create an absent notebook in one exact session. */"
          },
          {
            "kind": "method",
            "name": "environmentCatalog",
            "signature": "@Remote async environmentCatalog( request: NotebookEnvironmentCatalogRequest, signal: AbortSignal, ): Promise<NotebookRemoteResult<NotebookEnvironmentCatalog>>",
            "summary": "Read the environment catalog without activating a cold session.",
            "jsDoc": "/** Read the environment catalog without activating a cold session. */"
          },
          {
            "kind": "method",
            "name": "installUv",
            "signature": "@Remote async installUv(request: NotebookSessionRequest, signal: AbortSignal): Promise<NotebookRemoteResult<NotebookEnvironmentCatalog>>",
            "summary": "Install the private uv manager after explicit user intent.",
            "jsDoc": "/** Install the private uv manager after explicit user intent. */"
          },
          {
            "kind": "method",
            "name": "installPython",
            "signature": "@Remote async installPython( request: NotebookInstallPythonRequest, signal: AbortSignal, ): Promise<NotebookRemoteResult<NotebookEnvironmentCatalog>>",
            "summary": "Install the supported Python line after explicit user intent.",
            "jsDoc": "/** Install the supported Python line after explicit user intent. */"
          },
          {
            "kind": "method",
            "name": "createEnvironment",
            "signature": "@Remote async createEnvironment( request: NotebookCreateEnvironmentRequest, signal: AbortSignal, ): Promise<NotebookRemoteResult<NotebookEnvironmentCatalog>>",
            "summary": "Provision or explicitly claim one workspace environment.",
            "jsDoc": "/** Provision or explicitly claim one workspace environment. */"
          },
          {
            "kind": "method",
            "name": "attachEnvironment",
            "signature": "@Remote async attachEnvironment( request: NotebookAttachEnvironmentRequest, signal: AbortSignal, ): Promise<NotebookRemoteResult<NotebookDocument>>",
            "summary": "Attach a ready workspace environment and start its Jupyter kernel.",
            "jsDoc": "/** Attach a ready workspace environment and start its Jupyter kernel. */"
          },
          {
            "kind": "method",
            "name": "runtimeStatus",
            "signature": "@Remote async runtimeStatus( request: NotebookRuntimeStatusRequest, signal: AbortSignal, ): Promise<NotebookRemoteResult<NotebookKernelRuntimeStatus>>",
            "summary": "Read notebook runtime state without activating a cold session.",
            "jsDoc": "/** Read notebook runtime state without activating a cold session. */"
          },
          {
            "kind": "method",
            "name": "readAttachment",
            "signature": "@Remote async readAttachment( request: NotebookReadAttachmentRequest, signal: AbortSignal, ): Promise<NotebookRemoteResult<NotebookReadAttachmentAck>>",
            "summary": "Read one verified raster referenced by Notebook-owned durable events.",
            "jsDoc": "/** Read one verified raster referenced by Notebook-owned durable events. */"
          },
          {
            "kind": "method",
            "name": "editCell",
            "signature": "@Remote async editCell(request: NotebookEditCellRequest, signal: AbortSignal): Promise<NotebookRemoteResult<NotebookEditCellAck>>",
            "summary": "Replace one cell's source.",
            "jsDoc": "/** Replace one cell's source. */"
          },
          {
            "kind": "method",
            "name": "insertCell",
            "signature": "@Remote async insertCell( request: NotebookInsertCellRequest, signal: AbortSignal, ): Promise<NotebookRemoteResult<NotebookInsertCellAck>>",
            "summary": "Insert one cell after a stable predecessor, or at the start.",
            "jsDoc": "/** Insert one cell after a stable predecessor, or at the start. */"
          },
          {
            "kind": "method",
            "name": "runCell",
            "signature": "@Remote async runCell(request: NotebookRunCellRequest, signal: AbortSignal): Promise<NotebookRemoteResult<NotebookRunAck>>",
            "summary": "Execute one cell and inject its bounded result into the initiating Agent.",
            "jsDoc": "/** Execute one cell and inject its bounded result into the initiating Agent. */"
          },
          {
            "kind": "method",
            "name": "restart",
            "signature": "@Remote async restart(request: NotebookIdentityRequest, signal: AbortSignal): Promise<NotebookRemoteResult<NotebookKernelAck>>",
            "summary": "Replace one notebook kernel while retaining its environment.",
            "jsDoc": "/** Replace one notebook kernel while retaining its environment. */"
          },
          {
            "kind": "method",
            "name": "reload",
            "signature": "@Remote async reload(request: NotebookIdentityRequest, signal: AbortSignal): Promise<NotebookRemoteResult<NotebookReloadAck>>",
            "summary": "Accept the current external file revision.",
            "jsDoc": "/** Accept the current external file revision. */"
          },
          {
            "kind": "method",
            "name": "interrupt",
            "signature": "@Remote async interrupt(request: NotebookInterruptRequest): Promise<NotebookRemoteResult<NotebookInterruptAck>>",
            "summary": "Interrupt the active execution for one notebook.",
            "jsDoc": "/** Interrupt the active execution for one notebook. */"
          }
        ],
        "types": [
          {
            "name": "CellId",
            "declaration": "export type CellId = string;"
          },
          {
            "name": "CellType",
            "declaration": "export type CellType = 'code' | 'markdown' | 'raw';"
          },
          {
            "name": "ExecutionId",
            "declaration": "export type ExecutionId = string;"
          },
          {
            "name": "NotebookAttachEnvironmentRequest",
            "declaration": "export interface NotebookAttachEnvironmentRequest {\n    readonly sessionId: string;\n    readonly notebookId: NotebookId;\n    readonly environmentId: NotebookEnvironmentId;\n}"
          },
          {
            "name": "NotebookCell",
            "declaration": "export interface NotebookCell {\n    readonly id: CellId;\n    readonly cellType: CellType;\n    readonly source: string;\n    readonly metadata: NotebookJsonObject;\n    readonly attachments: NotebookCellAttachments;\n    readonly outputs: readonly NotebookOutput[];\n    readonly executionCount?: number;\n    readonly status?: 'running' | 'ok' | 'error' | 'cancelled';\n    readonly error?: string;\n}"
          },
          {
            "name": "NotebookCellAttachments",
            "declaration": "export type NotebookCellAttachments = Readonly<Record<string, NotebookMimeBundle>>;"
          },
          {
            "name": "NotebookCreateEnvironmentRequest",
            "declaration": "export interface NotebookCreateEnvironmentRequest {\n    readonly sessionId: string;\n    readonly environmentId: NotebookEnvironmentId;\n    readonly allowExisting: boolean;\n    readonly rebuild: boolean;\n}"
          },
          {
            "name": "NotebookCreateRequest",
            "declaration": "export interface NotebookCreateRequest {\n    readonly sessionId: string;\n    readonly path: string;\n}"
          },
          {
            "name": "NotebookDiscoverRequest",
            "declaration": "export interface NotebookDiscoverRequest {\n    readonly sessionId: string;\n    readonly after?: string;\n}"
          },
          {
            "name": "NotebookDiscoveryItem",
            "declaration": "export interface NotebookDiscoveryItem {\n    readonly path: string;\n    readonly size?: number;\n}"
          },
          {
            "name": "NotebookDiscoveryPage",
            "declaration": "export interface NotebookDiscoveryPage {\n    readonly items: readonly NotebookDiscoveryItem[];\n    readonly nextAfter?: string;\n    readonly partial: boolean;\n}"
          },
          {
            "name": "NotebookDocument",
            "declaration": "export interface NotebookDocument {\n    readonly id: NotebookId;\n    readonly path: string;\n    readonly kernel?: NotebookKernelSelection;\n    readonly fileVersion: NotebookFileVersion;\n    readonly nbformatMinor: number;\n    readonly metadata: NotebookJsonObject;\n    readonly cells: readonly NotebookCell[];\n}"
          },
          {
            "name": "NotebookEditCellAck",
            "declaration": "export interface NotebookEditCellAck {\n    readonly ok: true;\n}"
          },
          {
            "name": "NotebookEditCellRequest",
            "declaration": "export interface NotebookEditCellRequest {\n    readonly sessionId: string;\n    readonly notebookId: NotebookId;\n    readonly cellId: CellId;\n    readonly source: string;\n}"
          },
          {
            "name": "NotebookEnvironmentCatalog",
            "declaration": "export interface NotebookEnvironmentCatalog {\n    readonly manager: NotebookEnvironmentManagerCatalog;\n    readonly pythons: readonly NotebookPythonCatalogEntry[];\n    readonly environments: readonly NotebookEnvironmentCatalogEntry[];\n}"
          },
          {
            "name": "NotebookEnvironmentCatalogEntry",
            "declaration": "export interface NotebookEnvironmentCatalogEntry {\n    readonly id: NotebookEnvironmentId;\n    readonly displayName: string;\n    readonly status: 'ready' | 'setup-required' | 'provisioning' | 'broken';\n    readonly pythonVersion?: string;\n    readonly managed: boolean;\n}"
          },
          {
            "name": "NotebookEnvironmentCatalogRequest",
            "declaration": "export interface NotebookEnvironmentCatalogRequest {\n    readonly sessionId: string;\n}"
          },
          {
            "name": "NotebookEnvironmentId",
            "declaration": "export type NotebookEnvironmentId = string;"
          },
          {
            "name": "NotebookEnvironmentManagerCatalog",
            "declaration": "export interface NotebookEnvironmentManagerCatalog {\n    readonly status: 'ready' | 'missing' | 'broken' | 'unsupported';\n    readonly version?: string;\n    readonly canInstall: boolean;\n}"
          },
          {
            "name": "NotebookFileVersion",
            "declaration": "export type NotebookFileVersion = string;"
          },
          {
            "name": "NotebookId",
            "declaration": "export type NotebookId = string;"
          },
          {
            "name": "NotebookIdentityRequest",
            "declaration": "export interface NotebookIdentityRequest {\n    readonly sessionId: string;\n    readonly notebookId: NotebookId;\n}"
          },
          {
            "name": "NotebookImageAttachmentRef",
            "declaration": "export interface NotebookImageAttachmentRef {\n    readonly attachmentId: string;\n    readonly mediaType: string;\n    readonly bytes: number;\n    readonly width: number;\n    readonly height: number;\n    readonly name?: string;\n}"
          },
          {
            "name": "NotebookInsertCellAck",
            "declaration": "export interface NotebookInsertCellAck {\n    readonly cellId: CellId;\n}"
          },
          {
            "name": "NotebookInsertCellRequest",
            "declaration": "export interface NotebookInsertCellRequest {\n    readonly sessionId: string;\n    readonly notebookId: NotebookId;\n    readonly cellType: CellType;\n    readonly afterCellId?: CellId;\n    readonly source?: string;\n}"
          },
          {
            "name": "NotebookInstallPythonRequest",
            "declaration": "export interface NotebookInstallPythonRequest {\n    readonly sessionId: string;\n    readonly version: '3.12';\n}"
          },
          {
            "name": "NotebookInterruptAck",
            "declaration": "export interface NotebookInterruptAck {\n    readonly interrupted: boolean;\n}"
          },
          {
            "name": "NotebookInterruptRequest",
            "declaration": "export interface NotebookInterruptRequest extends NotebookIdentityRequest {\n    readonly reason?: string;\n}"
          },
          {
            "name": "NotebookJsonObject",
            "declaration": "export interface NotebookJsonObject {\n    readonly [key: string]: NotebookJsonValue;\n}"
          },
          {
            "name": "NotebookJsonValue",
            "declaration": "export type NotebookJsonValue = null | boolean | number | string | readonly NotebookJsonValue[] | NotebookJsonObject;"
          },
          {
            "name": "NotebookKernelAck",
            "declaration": "export interface NotebookKernelAck {\n    readonly notebookId: NotebookId;\n    readonly environmentId: NotebookEnvironmentId;\n    readonly backend: string;\n    readonly kernelName?: string;\n    readonly generation: number;\n}"
          },
          {
            "name": "NotebookKernelRuntimeStatus",
            "declaration": "export type NotebookKernelRuntimeStatus = { readonly status: 'detached'; } | { readonly status: 'starting' | 'ready' | 'running' | 'stopped'; readonly environmentId: NotebookEnvironmentId; } | { readonly status: 'failed'; readonly environmentId: NotebookEnvironmentId; readonly message: string; };"
          },
          {
            "name": "NotebookKernelSelection",
            "declaration": "export interface NotebookKernelSelection {\n    readonly environmentId: NotebookEnvironmentId;\n    readonly backend: string;\n    readonly kernelName?: string;\n    readonly generation: number;\n}"
          },
          {
            "name": "NotebookMimeBundle",
            "declaration": "export type NotebookMimeBundle = Readonly<Record<string, NotebookMimeValue>>;"
          },
          {
            "name": "NotebookMimeValue",
            "declaration": "export type NotebookMimeValue = { readonly type: 'text'; readonly text: string; } | { readonly type: 'json'; readonly value: NotebookJsonValue; } | { readonly type: 'image'; readonly attachment: NotebookImageAttachmentRef; } | { readonly type: 'base64'; readonly data: string; };"
          },
          {
            "name": "NotebookOpenRequest",
            "declaration": "export interface NotebookOpenRequest {\n    readonly sessionId: string;\n    readonly path: string;\n}"
          },
          {
            "name": "NotebookOutput",
            "declaration": "export type NotebookOutput = { readonly type: 'stream'; readonly name: 'stdout' | 'stderr'; readonly text: string; } | { readonly type: 'display'; readonly data: NotebookMimeBundle; readonly metadata: NotebookJsonObject; readonly displayId?: string; } | { readonly type: 'execute-result'; readonly data: NotebookMimeBundle; readonly metadata: NotebookJsonObject; readonly executionCount: number | null; readonly displayId?: string; } | { readonly type: 'error'; readonly name: string; readonly value: string; readonly traceback: readonly string[]; };"
          },
          {
            "name": "NotebookPythonCatalogEntry",
            "declaration": "export interface NotebookPythonCatalogEntry {\n    readonly id: string;\n    readonly version: string;\n    readonly source: 'configured' | 'path' | 'managed';\n}"
          },
          {
            "name": "NotebookReadAttachmentAck",
            "declaration": "export interface NotebookReadAttachmentAck {\n    readonly attachment: NotebookImageAttachmentRef;\n    readonly data: string;\n}"
          },
          {
            "name": "NotebookReadAttachmentRequest",
            "declaration": "export interface NotebookReadAttachmentRequest {\n    readonly sessionId: string;\n    readonly attachmentId: string;\n}"
          },
          {
            "name": "NotebookReloadAck",
            "declaration": "export interface NotebookReloadAck {\n    readonly fileVersion: NotebookFileVersion;\n}"
          },
          {
            "name": "NotebookRemoteError",
            "declaration": "export interface NotebookRemoteError {\n    readonly source: 'session' | 'core' | 'persistence' | 'environment' | 'attachment' | 'configuration' | 'cancelled';\n    readonly code: string;\n    readonly message: string;\n    readonly category?: string;\n    readonly retryable?: boolean;\n}"
          },
          {
            "name": "NotebookRemoteResult",
            "declaration": "export type NotebookRemoteResult<T> = { readonly ok: true; readonly value: T; } | { readonly ok: false; readonly error: NotebookRemoteError; };"
          },
          {
            "name": "NotebookRunAck",
            "declaration": "export interface NotebookRunAck {\n    readonly executionId: ExecutionId;\n    readonly status: 'ok' | 'error' | 'cancelled';\n    readonly executionCount: number | null;\n    readonly error?: string;\n}"
          },
          {
            "name": "NotebookRunCellRequest",
            "declaration": "export interface NotebookRunCellRequest {\n    readonly sessionId: string;\n    readonly notebookId: NotebookId;\n    readonly cellId: CellId;\n    readonly source?: string;\n}"
          },
          {
            "name": "NotebookRuntimeStatusRequest",
            "declaration": "export interface NotebookRuntimeStatusRequest {\n    readonly sessionId: string;\n    readonly notebookId: NotebookId;\n}"
          },
          {
            "name": "NotebookSessionRequest",
            "declaration": "export interface NotebookSessionRequest {\n    readonly sessionId: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
